# Generated by Django 2.1.3 on 2018-12-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default='Do you think this is a greate idea?'),
        ),
    ]
