# Generated by Django 2.1.3 on 2018-12-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
    ]
