# Generated by Django 2.1.3 on 2018-12-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0003_choice_votes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='admin_token',
            field=models.TextField(default='9ot61xh3'),
        ),
    ]
